print ('Acontinuacion usted podrá sumar')
print ('Ingrese primer numero')
dato1 = input()
dato1 = float (dato1)
print ('Ingrese segundo numero')
dato2 = input()
dato2 = float (dato2)
dato3 = dato1 + dato2
dato3 = float (dato3)
print('su suma es',dato3)
print ('Acontinuacion usted podrá sacar un promedio')
nota1 = float(input("Ingrese nota 1 "))
nota2 = float(input("Ingrese nota 2 "))
nota3 = float(input("Ingrese nota 3 "))
promedio = float((nota1+nota2+nota3)/3)
print ('su promedio es', promedio)
